name: Sync

on:
  schedule:
    # 15 minutes after josh/imdb-data runs
    # https://github.com/josh/imdb-data/blob/61b99a9/.github/workflows/sync.yml#L5C5-L5C32
    - cron: "30 0,5,19,23 * * *"
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-slim
    concurrency: sync

    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3

      - uses: astral-sh/setup-uv@08807647e7069bb48b6ef5acd8ec9567f424441b # v8.1.0

      - name: Install dependencies
        run: uv sync

      - name: Sync
        run: |
          uv run imdb-plex-sync
        env:
          IMDB_WATCHLIST_URL: ${{ vars.IMDB_WATCHLIST_URL }}
          PLEX_TOKEN: ${{ secrets.PLEX_TOKEN }}
