name: Test

on:
  push:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-slim

    strategy:
      matrix:
        uv_resolution: ["highest", "lowest-direct"]

    env:
      UV_RESOLUTION: ${{ matrix.uv_resolution }}

    steps:
      - name: Checkout main branch
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3

      - uses: astral-sh/setup-uv@08807647e7069bb48b6ef5acd8ec9567f424441b # v8.1.0

      - name: Install dependencies
        run: uv sync

      - name: Sync (Dry Run)
        run: |
          uv run imdb-plex-sync --dry-run
        env:
          IMDB_WATCHLIST_URL: ${{ vars.IMDB_WATCHLIST_URL }}
          PLEX_TOKEN: ${{ secrets.PLEX_TOKEN }}
